In [1]:
#!jupyter nbconvert --to script ScrapeDataCleaning.ipynb

In [2]:
import pandas as pd
import numpy as np
import re
import pickle
from datetime import datetime

In [3]:
with open('listings_all.pickle', 'rb') as file:
    listings = pickle.load(file)

In [4]:
listings = pd.DataFrame(listings)

In [5]:
listings.head()

,cost,datetime,extra_info,id,last_pos_time,latitude,link,longitude,place,size,text,title
0,$3300,"[2018-10-15 4:37pm, 2018-10-24 7:02pm]",\n\n2BR / 2.5Ba\n1564ft2\navailable oct 31\n\n...,6724361608,2018-10-24 19:07,37.402847,https://sfbay.craigslist.org/sby/apa/d/north-s...,-121.924755,(san jose north),2br -\n 1564ft2 -,QR Code Link to This Post\n\n\nBRAND NEW REMOD...,North San Jose River Oaks Area 95134 Fully RE...
1,$2399,[],,6731996825,2018-10-24 19:06,None,https://sfbay.craigslist.org/nby/apa/d/get-hap...,None,(novato),2br -\n 1028ft2 -,None,"Get Happy, Lease Now At The Vineyard Apartment..."
2,$3300,"[2018-10-17 12:04am, 2018-10-24 7:02pm]",\n\n2BR / 2.5Ba\n1564ft2\navailable oct 31\n\n...,6725407723,2018-10-24 19:06,37.402847,https://sfbay.craigslist.org/sby/apa/d/north-s...,-121.924755,(san jose north),2br -\n 1564ft2 -,QR Code Link to This Post\n\n\nBRAND NEW REMOD...,North San Jose in River Oaks Area 95134 Fully ...
3,$2875,[2018-10-24 7:02pm],\n\n2BR / 1Ba\n1750ft2\navailable dec 1\n\ntow...,6732006789,2018-10-24 19:06,37.901258,https://sfbay.craigslist.org/eby/apa/d/best-va...,-122.308644,(albany / el cerrito),2br -\n 1750ft2 -,QR Code Link to This Post\n\n\nFresh! Spacious...,Best Value! 2+ Bedroom Townhouse
4,$3695,[2018-10-24 7:02pm],\n\n1BR / 1Ba\n\napartment\n\nlaundry in bldg\...,6732006575,2018-10-24 19:06,37.796670,https://sfbay.craigslist.org/sfc/apa/d/large-1...,-122.438779,(marina / cow hollow),1br -,QR Code Link to This Post\n\n\nPlease contact:...,Large 1 bedroom in trendy Cow Hollow. Approxim...

In [6]:
listings

,cost,datetime,extra_info,id,last_pos_time,latitude,link,longitude,place,size,text,title
0,$3300,"[2018-10-15 4:37pm, 2018-10-24 7:02pm]",\n\n2BR / 2.5Ba\n1564ft2\navailable oct 31\n\n...,6724361608,2018-10-24 19:07,37.402847,https://sfbay.craigslist.org/sby/apa/d/north-s...,-121.924755,(san jose north),2br -\n 1564ft2 -,QR Code Link to This Post\n\n\nBRAND NEW REMOD...,North San Jose River Oaks Area 95134 Fully RE...
1,$2399,[],,6731996825,2018-10-24 19:06,None,https://sfbay.craigslist.org/nby/apa/d/get-hap...,None,(novato),2br -\n 1028ft2 -,None,"Get Happy, Lease Now At The Vineyard Apartment..."
2,$3300,"[2018-10-17 12:04am, 2018-10-24 7:02pm]",\n\n2BR / 2.5Ba\n1564ft2\navailable oct 31\n\n...,6725407723,2018-10-24 19:06,37.402847,https://sfbay.craigslist.org/sby/apa/d/north-s...,-121.924755,(san jose north),2br -\n 1564ft2 -,QR Code Link to This Post\n\n\nBRAND NEW REMOD...,North San Jose in River Oaks Area 95134 Fully ...
3,$2875,[2018-10-24 7:02pm],\n\n2BR / 1Ba\n1750ft2\navailable dec 1\n\ntow...,6732006789,2018-10-24 19:06,37.901258,https://sfbay.craigslist.org/eby/apa/d/best-va...,-122.308644,(albany / el cerrito),2br -\n 1750ft2 -,QR Code Link to This Post\n\n\nFresh! Spacious...,Best Value! 2+ Bedroom Townhouse
4,$3695,[2018-10-24 7:02pm],\n\n1BR / 1Ba\n\napartment\n\nlaundry in bldg\...,6732006575,2018-10-24 19:06,37.796670,https://sfbay.craigslist.org/sfc/apa/d/large-1...,-122.438779,(marina / cow hollow),1br -,QR Code Link to This Post\n\n\nPlease contact:...,Large 1 bedroom in trendy Cow Hollow. Approxim...
5,$1649,"[2018-09-26 1:35pm, 2018-10-24 7:00pm]",\n\n1BR / 1Ba\n708ft2\n\napartment,6708276388,2018-10-24 19:05,38.008321,https://sfbay.craigslist.org/eby/apa/d/pittsbu...,-121.864673,None,1br -\n 708ft2 -,QR Code Link to This Post\n\n\nDiamond Hillsid...,"❄ Pittsburg apartment for rent, Additional Sto..."
6,$2443,[2018-10-24 7:01pm],\n\n1BR / 1Ba\n798ft2\n\ncats are OK - purrr\n...,6732006200,2018-10-24 19:05,37.553177,https://sfbay.craigslist.org/eby/apa/d/you-sho...,-121.975581,(fremont / union city / newark),1br -\n 798ft2 -,QR Code Link to This Post\n\n\nCall Us Today ...,You Should See This!
7,$1800,"[2018-10-05 1:24pm, 2018-10-24 6:59pm]",\n\n2BR / 1Ba\n923ft2\navailable oct 1\n\napar...,6715912752,2018-10-24 19:04,38.002095,https://sfbay.craigslist.org/eby/apa/d/2-bed-1...,-121.822462,(pittsburg / antioch),2br -\n 923ft2 -,QR Code Link to This Post\n\n\nNice and clean ...,2 Bed/ 1 Bath Townhome $1800/month
8,$1450,[2018-10-24 7:00pm],\n\n2BR / 2Ba\n972ft2\n\napartment\n\nw/d in u...,6732005433,2018-10-24 19:04,37.349200,https://sfbay.craigslist.org/sby/apa/d/1450-ro...,-121.953000,(santa clara),2br -\n 972ft2 -,"QR Code Link to This Post\n\n\nQuiet, professi...",$1450 / room available in 2 bed/2 bath apartment
9,$800,[2018-10-24 6:47pm],\n\ncats are OK - purrr\n\ndogs are OK - wooof...,6731999038,2018-10-24 19:03,38.006600,https://sfbay.craigslist.org/eby/apa/d/1-bedro...,-122.263700,"(hercules, pinole, san pablo, el sob)",None,QR Code Link to This Post\n\n\nNew renovations...,1 bedroom + Den hercules
10,$1800,"[2018-10-05 1:23pm, 2018-10-24 6:57pm]",\n\n2BR / 1Ba\n925ft2\navailable oct 25\n\napa...,6715912032,2018-10-24 19:02,38.002195,https://sfbay.craigslist.org/eby/apa/d/2-bedro...,-121.822439,(pittsburg / antioch),2br -\n 925ft2 -,QR Code Link to This Post\n\n\nUpdated 2 bedro...,2 Bedroom 1 Bath Townhome
11,$1050,[],,6731993919,2018-10-24 19:02,None,https://sfbay.craigslist.org/nby/apa/d/enjoy-l...,None,(fairfax),2br -\n 990ft2 -,None,ENJOY LUXURY LIFESTYLE LIVING IN A COZY APARTM...
12,$2999,"[2018-10-20 5:56pm, 2018-10-24 6:57pm]",\n\n1BR / 1Ba\n783ft2\navailable oct 20\n\ncat...,6728630123,2018-10-24 19:02,37.411674,https://sfbay.craigslist.org/sby/apa/d/1-bed-1...,-121.898987,None,1br -\n 783ft2 -,QR Code Link to This Post\n\n\nTuring is the f...,"1 Bed - 1 Bath, Central A/C & Heating, Expansi..."
13,$4198,"[2018-10-05 10:40am, 2018-10-24 6:56pm]",\n\n2BR / 1Ba\navailable oct 6\n\ncats are OK ...,6715734370,2018-10-24 19:01,37.778256,https://sfbay.craigslist.org/sfc/apa/d/designe...,-122.434716,(alamo square / nopa),2br -,QR Code Link to This Post\n\n\nNewly Remodeled...,Designer Finishes in the heart of Alamo Square
14,$2895,[2018-10-24 6:57pm],\n\n0BR / 1Ba\n\ncondo\n\nw/d in unit\n\nstree...,6732004190,2018-10-24 19:01,37.762700,https://sfbay.craigslist.org/sfc/apa/d/studio-...,-122.442229,(castro / upper market),None,QR Code Link to This Post\n\n\nPlease contact:...,"Studio with built ins, private deck, washer/dr..."
15,$1650,[2018-10-24 6:09pm],\n\n2BR / 2Ba\n1196ft2\navailable dec 1\n\napa...,6731978538,2018-10-24 18:59,37.887915,https://sfbay.craigslist.org/nby/apa/d/master-...,-122.509528,(mill valley),2br -\n 1196ft2 -,QR Code Link to This Post\n\n\nLooking for a n...,Master Bedroom Available in 2 Bed/2 Bath Apart...
16,$28,[2018-10-24 6:55pm],\n\navailable oct 25\n\nmanufactured\n\nno lau...,6732003183,2018-10-24 18:59,37.750900,https://sfbay.craigslist.org/sby/apa/d/rent-it...,-122.415300,(mountain view),None,QR Code Link to This Post\n\n\nThis could be a...,Rent It or Buy It
17,$2500,[2018-10-24 6:54pm],\n\n1BR / 1Ba\n600ft2\navailable nov 1\n\ndogs...,6732002884,2018-10-24 18:58,37.860100,https://sfbay.craigslist.org/nby/apa/d/panoram...,-122.494600,(sausalito),1br -\n 600ft2 -,QR Code Link to This Post\n\n\nAVAILABLE NOVEM...,PANORAMIC WATER VIEWS/CONDO/PRIVATE ESTATE/CAB...
18,$3770,"[2018-10-17 4:45pm, 2018-10-24 6:53pm]",\n\n2BR / 2Ba\n866ft2\navailable nov 1\n\ncats...,6726098460,2018-10-24 18:58,37.655134,https://sfbay.craigslist.org/pen/apa/d/granite...,-122.491585,(pacifica),2br -\n 866ft2 -,QR Code Link to This Post\n\n\nOceanAire Apart...,"Granite Counter Tops, On-Line Rent Payment Sys..."
19,$3300,[2018-10-24 6:54pm],\n\napartment,6732002489,2018-10-24 18:58,37.759300,https://sfbay.craigslist.org/sfc/apa/d/appt-la...,-122.483600,(ingleside / SFSU / CCSF),None,QR Code Link to This Post\n\n\nFull Remodel\nn...,Appt LArge top Unit 2 bed 1 bath Full garage
20,$1900,"[2018-10-05 1:25pm, 2018-10-24 6:51pm]",\n\n2BR / 1Ba\n900ft2\navailable oct 15\n\ncat...,6715913225,2018-10-24 18:56,37.988121,https://sfbay.craigslist.org/eby/apa/d/cozy-up...,-122.042773,(concord / pleasant hill / martinez),2br -\n 900ft2 -,QR Code Link to This Post\n\n\nCozy Upstairs 2...,Cozy Upstairs 2 Bedroom 1 Bath
21,$1395,[2018-10-24 6:39pm],\n\n1BR / 1Ba\n533ft2\navailable oct 24\n\ncat...,6731995227,2018-10-24 18:56,37.743991,https://sfbay.craigslist.org/eby/apa/d/beautif...,-121.429858,(dublin / pleasanton / livermore),1br -\n 533ft2 -,QR Code Link to This Post\n\n\n*Rare availabil...,Beautiful floor work. Incredible spacious 1x1....
22,$3450,[2018-10-24 6:34pm],\n\n4BR / 2.5Ba\n2222ft2\navailable oct 13\n\n...,6731992459,2018-10-24 18:56,37.344537,https://sfbay.craigslist.org/sby/apa/d/per-mon...,-121.857838,(san jose downtown),4br -\n 2222ft2 -,QR Code Link to This Post\n\n\nContact info:DA...,"$3,450.00 per month - Newer San Jose Home for ..."
23,$3200,"[2018-10-17 11:15am, 2018-10-24 6:51pm]",\n\n4BR / 2Ba\n1500ft2\n\napartment\n\nlaundry...,6725795476,2018-10-24 18:56,37.795700,https://sfbay.craigslist.org/eby/apa/d/oakland...,-122.242900,(oakland lake merritt / grand),4br -\n 1500ft2 -,QR Code Link to This Post\n\n\nOakland New Chi...,Oakland New Chinatown Nice 3 bed 2 bath with 1...
24,$2650,[2018-10-24 6:52pm],\n\n2BR / 1.5Ba\n900ft2\n\ntownhouse\n\nw/d ho...,6732001633,2018-10-24 18:56,37.380497,https://sfbay.craigslist.org/sby/apa/d/great-l...,-122.054558,(sunnyvale),2br -\n 900ft2 -,QR Code Link to This Post\n\n\n900 sf\nRecentl...,Great location and price !
25,$4500,"[2018-10-07 10:20am, 2018-10-24 6:51pm]",\n\n5BR / 4Ba\n2405ft2\navailable jun 20\n\nho...,6717263179,2018-10-24 18:56,37.537336,https://sfbay.craigslist.org/eby/apa/d/5-bed-4...,-122.018872,(fremont / union city / newark),5br -\n 2405ft2 -,QR Code Link to This Post\n\n\nClose to Silico...,5 bed 4 bath New House for Rent
26,$2799,[2018-10-24 6:51pm],\n\n2BR / 2Ba\n1010ft2\navailable oct 24\n\nca...,6732001469,2018-10-24 18:55,37.558468,https://sfbay.craigslist.org/eby/apa/d/huge-2x...,-121.995997,(fremont / union city / newark),2br -\n 1010ft2 -,QR Code Link to This Post\n\n\nCamden Village\...,"Huge 2x2 Ready Now, A/C, W/D, Ask Us About Spe..."
27,$4050,[2018-10-24 6:51pm],\n\napartment\n\nw/d in unit\n\nno smoking\n\n...,6732001402,2018-10-24 18:55,37.418000,https://sfbay.craigslist.org/pen/apa/d/gorgeou...,-122.127400,(palo alto),None,QR Code Link to This Post\n\n\nPrime place to ...,"GORGEOUS 3 BD /1.5 BA, 1ST floor, with W/D in ..."
28,$3525,[2018-10-24 6:51pm],\n\n2BR / 1Ba\n800ft2\navailable oct 8\n\napar...,6732001149,2018-10-24 18:55,37.444300,https://sfbay.craigslist.org/pen/apa/d/2x1-ups...,-122.149700,(palo alto),2br -\n 800ft2 -,QR Code Link to This Post\n\n\nPlease come and...,"2x1 upstairs, downtown, blocks from University."
29,$2345,[2018-10-24 6:51pm],\n\napartment\n\nlaundry in bldg,6732001008,2018-10-24 18:55,37.418000,https://sfbay.craigslist.org/pen/apa/d/1x1-2nd...,-122.127400,(palo alto),None,QR Code Link to This Post\n\n\nPrime area to l...,"1x1, 2nd floor, you'll love this unit and loca..."
...,...,...,...,...,...,...,...,...,...,...,...,...
2970,$2638,[2018-10-24 12:34pm],\n\n1BR / 1Ba\n714ft2\navailable oct 24\n\ncat...,6731702548,2018-10-24 12:38,37.844026,https://sfbay.craigslist.org/eby/apa/d/love-th...,-122.295580,(emeryville),1br -\n 714ft2 -,"QR Code Link to This Post\n\n\n$2,638/mo #103\...",Love The Home You Live In! 1x1 Available NOW!
2971,$2445,[2018-10-24 12:24pm],\n\n2BR / 1Ba\n850ft2\navailable oct 27\n\ncat...,6731692166,2018-10-24 12:38,37.718829,https://sfbay.craigslist.org/eby/apa/d/beautif...,-122.147876,(san leandro),2br -\n 850ft2 -,QR Code Link to This Post\n\n\nBeautiful Fully...,BEAUTIFUL 2ND FLOOR VIEW!CHARMING & BRIGHT 2 B...
2972,$2300,"[2018-10-19 10:26am, 2018-10-24 12:33pm]",\n\n2BR / 1Ba\n903ft2\navailable oct 21\n\ncon...,6727441670,2018-10-24 12:38,37.584824,https://sfbay.craigslist.org/eby/apa/d/townhou...,-122.017539,(fremont / union city / newark),2br -\n 903ft2 -,QR Code Link to This Post\n\n\nTwo Story. Grea...,Townhouse style Condo
2973,$2346,[2018-10-24 12:34pm],\n\n0BR / 1Ba\n553ft2\navailable oct 24\n\ncat...,6731701735,2018-10-24 12:38,37.844026,https://sfbay.craigslist.org/eby/apa/d/top-flo...,-122.295580,(emeryville),553ft2 -,"QR Code Link to This Post\n\n\n$2,346/mo #428\...",TOP FLOOR Studio! This Comes With A Special Treat
2974,$2735,[2018-10-24 12:33pm],\n\n1BR / 1Ba\n531ft2\navailable oct 24\n\ncat...,6731701470,2018-10-24 12:37,37.384883,https://sfbay.craigslist.org/sby/apa/d/now-ava...,-122.003673,(sunnyvale),1br -\n 531ft2 -,QR Code Link to This Post\n\n\nVIEW OUR WEBSIT...,"Now Available, Private Garages, EV Chargers"
2975,$2400,[2018-10-24 12:33pm],\n\n2BR / 1Ba\navailable nov 1\n\napartment\n\...,6731701332,2018-10-24 12:37,37.789951,https://sfbay.craigslist.org/sfc/apa/d/1-2-bed...,-122.410433,(nob hill),2br -,"QR Code Link to This Post\n\n\nHi there,\nMy h...","1-2 Bedroom apartment, rent controlled in Nob ..."
2976,$1995,"[2018-10-09 12:09pm, 2018-10-24 12:32pm]",\n\n1BR / 1Ba\n600ft2\navailable nov 1\n\napar...,6719132893,2018-10-24 12:37,37.330468,https://sfbay.craigslist.org/sby/apa/d/huge-1-...,-121.883527,(Downtown San Jose),1br -\n 600ft2 -,QR Code Link to This Post\n\n\nOne bedroom/one...,HUGE 1 BEDROOM WALKING DISTANCE TO SJSU! NOV 1
2977,$1895,[2018-10-24 12:33pm],\n\n1BR / 1Ba\n560ft2\n\ncats are OK - purrr\n...,6731701099,2018-10-24 12:37,37.663004,https://sfbay.craigslist.org/eby/apa/d/move-in...,-121.865793,(dublin / pleasanton / livermore),1br -\n 560ft2 -,QR Code Link to This Post\n\n\nCommunity ameni...,Move in specials! 1x1 starting at $1895 and $1...
2978,$3080,[2018-10-24 12:33pm],\n\ntownhouse,6731700814,2018-10-24 12:37,37.349537,https://sfbay.craigslist.org/sby/apa/d/remodel...,-121.953499,(santa clara),None,QR Code Link to This Post\n\n\nTamarack Apartm...,Remodeled Townhouse! Awesome Location! Best Pl...
2979,$2650,"[2018-10-20 11:04am, 2018-10-24 12:32pm]",\n\n0BR / 1Ba\n424ft2\navailable nov 1\n\ncats...,6728312587,2018-10-24 12:37,37.655134,https://sfbay.craigslist.org/pen/apa/d/large-c...,-122.491585,(pacifica),424ft2 -,QR Code Link to This Post\n\n\nOceanAire Apart...,"Large Closets, Spacious Patio, Gorgeous Views!"
2980,$3132,[2018-10-24 12:33pm],\n\n3BR / 2Ba\n1194ft2\n\ncats are OK - purrr\...,6731700772,2018-10-24 12:37,37.763600,https://sfbay.craigslist.org/eby/apa/d/beautif...,-121.915500,(dublin / pleasanton / livermore),3br -\n 1194ft2 -,QR Code Link to This Post\n\n\nSeville2000 Bel...,Beautiful 3 bedroom apartment available soon!
2981,$3200,[2018-10-24 12:33pm],\n\n2BR / 1.5Ba\n976ft2\navailable oct 24\n\nc...,6731700636,2018-10-24 12:37,37.569135,https://sfbay.craigslist.org/pen/apa/d/2br-15b...,-122.265678,(foster city),2br -\n 976ft2 -,QR Code Link to This Post\n\n\n Every day is a...,2BR/1.5BA New Appliances!Hard Surface Flooring...
2982,$3861,[2018-10-24 12:33pm],\n\n3BR / 2Ba\n1421ft2\n\ncats are OK - purrr\...,6731700597,2018-10-24 12:37,37.530800,https://sfbay.craigslist.org/eby/apa/d/gorgeou...,-121.971200,(fremont / union city / newark),3br -\n 1421ft2 -,QR Code Link to This Post\n\n\nCall Us Today ...,Gorgeous carpeted 3 bedroom 2 bathroom apartme...
2983,$3411,[2018-10-24 12:32pm],\n\n2BR / 2Ba\n1089ft2\navailable nov 5\n\ncat...,6731700458,2018-10-24 12:36,37.844026,https://sfbay.craigslist.org/eby/apa/d/trick-o...,-122.295580,(emeryville),2br -\n 1089ft2 -,"QR Code Link to This Post\n\n\n$3,411/MO 245\n...",Trick Or Treat Into Savings! Coming Available ...
2984,$2430,[2018-10-24 12:32pm],\n\ncats are OK - purrr\n\napartment\n\nlaundr...,6731700402,2018-10-24 12:36,37.349537,https://sfbay.craigslist.org/sby/apa/d/remodel...,-121.953499,(santa clara),None,QR Code Link to This Post\n\n\n Welcome Home t...,Remodeled One Bedroom Nestled in the Heart of ...
2985,$1690,"[2018-10-06 9:54am, 2018-10-24 12:32pm]",\n\n1BR / 1Ba\n559ft2\navailable oct 24\n\ncat...,6716535005,2018-10-24 12:36,38.409289,https://sfbay.craigslist.org/nby/apa/d/special...,-122.712741,(santa rosa),1br -\n 559ft2 -,QR Code Link to This Post\n\n\nVineyard Garden...,Special Low Pricing on Homes Ready Now! $500 d...
2986,$2395,"[2018-10-08 11:32am, 2018-10-24 12:31pm]",\n\n2BR / 1.5Ba\navailable oct 8\n\napartment\...,6718158989,2018-10-24 12:36,37.859052,https://sfbay.craigslist.org/eby/apa/d/moraga-...,-122.128765,(lafayette / orinda / moraga),2br -,QR Code Link to This Post\n\n\n1989 Ascot Driv...,Moraga Townhouse Available Now
2987,$1895,"[2018-10-22 11:28am, 2018-10-24 12:31pm]",\n\n1BR / 1Ba\n560ft2\n\ncats are OK - purrr\n...,6729851461,2018-10-24 12:36,37.663004,https://sfbay.craigslist.org/eby/apa/d/move-in...,-121.865793,(dublin / pleasanton / livermore),1br -\n 560ft2 -,QR Code Link to This Post\n\n\nCommunity ameni...,Move in Specials!! 1x1 starting at $1895 and $...
2988,$3995,[2018-10-24 12:32pm],\n\n1BR / 2Ba\n1147ft2\navailable oct 24\n\nca...,6731700074,2018-10-24 12:36,37.324542,https://sfbay.craigslist.org/sby/apa/d/last-1-...,-122.008870,(cupertino),1br -\n 1147ft2 -,QR Code Link to This Post\n\n\nMADE IN CUPERTI...,Last 1 Bed + 2 Bath Loft! Walk-able Town Squar...
2989,$1795,"[2018-10-17 1:01pm, 2018-10-24 12:31pm]",\n\n0BR / 1Ba\n295ft2\navailable nov 26\n\napa...,6725907043,2018-10-24 12:36,37.352872,https://sfbay.craigslist.org/sby/apa/d/cozy-1s...,-121.987039,(santa clara),295ft2 -,QR Code Link to This Post\n\n\nContact info: \...,Cozy 1st floor Studio available in
2990,$11000,"[2018-10-24 1:22pm, 2018-10-24 12:32pm]",\n\n4BR / 4Ba\n3300ft2\navailable dec 1\n\ncat...,6731699829,2018-10-24 12:36,37.878326,https://sfbay.craigslist.org/nby/apa/d/amazing...,-122.522885,(mill valley),4br -\n 3300ft2 -,"QR Code Link to This Post\n\n\nA custom, large...",Amazing Mill Valley Home Available
2991,$4500,"[2018-10-19 1:29am, 2018-10-24 12:31pm]",\n\n4BR / 2.5Ba\n1820ft2\navailable oct 1\n\nc...,6727110324,2018-10-24 12:36,37.840426,https://sfbay.craigslist.org/eby/apa/d/reduced...,-122.197578,(oakland hills / mills),4br -\n 1820ft2 -,QR Code Link to This Post\n\n\nThis home has a...,Reduced rent 3 level epic home with VIEW
2992,$5100,"[2018-10-24 12:32pm, 2018-10-24 12:37pm]",\n\n3BR / 1.5Ba\n1700ft2\navailable nov 3\n\nc...,6731699616,2018-10-24 12:36,37.531936,https://sfbay.craigslist.org/pen/apa/d/gorgeou...,-122.308480,(san mateo),3br -\n 1700ft2 -,"QR Code Link to This Post\n\n\nHello,\n\nRenti...",Gorgeous house for rent
2993,$1900,[2018-10-24 12:31pm],\n\n1BR / 2Ba\n700ft2\n\ncats are OK - purrr\n...,6731699399,2018-10-24 12:35,37.970926,https://sfbay.craigslist.org/nby/apa/d/large-s...,-122.533758,(san rafael),1br -\n 700ft2 -,QR Code Link to This Post\n\n\nTwo full Bathro...,Large Studio Apartment for Rent
2994,$5389,[2018-10-24 12:31pm],\n\n2BR / 2Ba\n1097ft2\navailable oct 24\n\nop...,6731699271,2018-10-24 12:35,37.396734,https://sfbay.craigslist.org/sby/apa/d/come-lo...,-122.011791,(sunnyvale),2br -\n 1097ft2 -,"QR Code Link to This Post\n\n\n6Ten, managed b...","Come Look and Lease, Auto Charging Stations, P..."
2995,$6295,"[2018-09-28 10:39am, 2018-10-24 12:30pm]",\n\n4BR / 4Ba\n2500ft2\navailable oct 4\n\ncat...,6709811088,2018-10-24 12:35,37.757306,https://sfbay.craigslist.org/sfc/apa/d/new-spa...,-122.491737,(sunset / parkside),4br -\n 2500ft2 -,QR Code Link to This Post\n\n\nThis tastefully...,New Spanish Colonial House with ALL Utilities...
2996,$1900,[2018-10-24 12:31pm],\n\n1BR / 2Ba\n700ft2\n\ncats are OK - purrr\n...,6731698930,2018-10-24 12:35,37.970926,https://sfbay.craigslist.org/nby/apa/d/large-s...,-122.533758,(san rafael),1br -\n 700ft2 -,QR Code Link to This Post\n\n\nTwo full Bathro...,Large Studio Apartment for Rent
2997,$3995,"[2018-10-04 4:10pm, 2018-10-24 12:30pm]",\n\n2BR / 1Ba\navailable oct 4\n\napartment\n\...,6715176436,2018-10-24 12:35,37.785248,https://sfbay.craigslist.org/sfc/apa/d/large-2...,-122.439873,(pacific heights),2br -,QR Code Link to This Post\n\n\nBrilliant top f...,Large 2Bd/1Ba in Pacific Heights FREE Parking:
2998,$4072,[2018-10-24 12:31pm],\n\n1BR / 1Ba\n658ft2\navailable oct 24\n\ncat...,6731698797,2018-10-24 12:35,37.769428,https://sfbay.craigslist.org/sfc/apa/d/best-pr...,-122.403979,None,1br -\n 658ft2 -,QR Code Link to This Post\n\n\nCall Us Today ...,"Best Price 1 Bed - Huge Windows, Historic View..."
2999,$2350,[2018-10-24 12:31pm],\n\n0BR / 1Ba\n\napartment\n\nlaundry in bldg\...,6731698620,2018-10-24 12:35,37.800206,https://sfbay.craigslist.org/sfc/apa/d/cow-hol...,-122.426001,(marina / cow hollow),None,QR Code Link to This Post\n\n\nPlease contact:...,"Cow Hollow studio w/upgraded kit, hrwd fls, di..."

In [7]:
listings.isnull().sum()

cost               2
datetime           0
extra_info         0
id                 0
last_pos_time      0
latitude          17
link               0
longitude         17
place            101
size             133
text              11
title              0
dtype: int64

__Cleaning Cost__

In [8]:
cost = []
for i in listings['cost'].values:
    try:
        val = int(re.findall('\w+',i)[0])
    except:
        print(i)
        val = i
    cost.append(val)

None
None

In [9]:
cost = pd.Series(cost, name = 'cost')

In [10]:
cost.head()

0    3300.0
1    2399.0
2    3300.0
3    2875.0
4    3695.0
Name: cost, dtype: float64

__Cleaning DateTime__

In [11]:
date_time_ser = listings.datetime.values
date_time_list = []
for i in date_time_ser:
    date_time_dict = dict.fromkeys(['datetime_posted', 'datetime_update'])
    date_time_len = len(i)
    if date_time_len>2: print(i)
    if date_time_len==0:
        date_time_list.append(date_time_dict)
    else :
        datetime0 = datetime.strptime(i[0], '%Y-%m-%d %I:%M%p')
        if date_time_len==1:
            date_time_dict['datetime_posted'] = datetime0
        else :
            datetime1 = datetime.strptime(i[1], '%Y-%m-%d %I:%M%p')
            if datetime0<datetime1:
                date_time_dict['datetime_posted'] = datetime0
                date_time_dict['datetime_update'] = datetime1
            else:
                date_time_dict['datetime_posted'] = datetime1
                date_time_dict['datetime_update'] = datetime0
        date_time_list.append(date_time_dict)

In [12]:
date_time_df = pd.DataFrame(date_time_list)

In [13]:
date_time_df.head()

      datetime_posted     datetime_update
0 2018-10-15 16:37:00 2018-10-24 19:02:00
1                 NaT                 NaT
2 2018-10-17 00:04:00 2018-10-24 19:02:00
3 2018-10-24 19:02:00                 NaT
4 2018-10-24 19:02:00                 NaT

__Cleaning extra_info__

In [14]:
ex_info = listings.extra_info.values.tolist()

In [15]:
def extract_size(string):
    ba = re.findall('([\w\.]+)Ba', string)
    br = re.findall('([\w\.]+)BR', string)
    sz = re.findall('([\w]+)ft2', string)
    try:
        av = re.findall('available\s*([\w ]+)', string)[0]
    except:
        av = None
    size = []
    for i in [br, ba, sz]:
        try: 
            k = float(i[0])
        except:
            k = None
        size.append(k)
    size.append(av)
    return(size)

In [16]:
def clean_extra_info(string):
    str_list = string.strip().split('\n\n')
    Br, Ba, size, available = extract_size(string)
    if len(str_list)>0:
        flag = True if any(x in string for x in ['Ba', 'BR', 'ft2', 'available']) else False
        if flag:
            other = ' '.join([i.replace(' ', '-') for i in str_list[1:]])
        else:
            other = ' '.join([i.replace(' ', '-') for i in str_list])
    else: other = ''
    return([Br, Ba, size, available, other])

In [112]:
extra_info_dict = []
for i in ex_info:
    Br, Ba, size, available, other = clean_extra_info(i)
    extra_info_dict.append({'bedroom': Br, 'bathroom': Ba, 'size_house': size, 'availability': available, 'other_info': other})

In [113]:
extra_info_df = pd.DataFrame(extra_info_dict)

In [114]:
extra_info_df.head()

,availability,bathroom,bedroom,other_info,size_house
0,oct 31,2.5,2.0,townhouse w/d-in-unit no-smoking attached-garage,1564.0
1,None,NaN,NaN,,NaN
2,oct 31,2.5,2.0,townhouse w/d-in-unit no-smoking attached-garage,1564.0
3,dec 1,1.0,2.0,townhouse w/d-in-unit no-smoking attached-garage,1750.0
4,None,1.0,1.0,apartment laundry-in-bldg street-parking,NaN

__Tokenizing other_info__

In [39]:
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
corpus_other_info = extra_info_df['other_info'].values

In [69]:
vocab_other_info = []
for i in ' '.join(corpus_other_info.tolist()).split(' '):
    if i == '' or len(re.findall('[0-9]+', i))>0: continue
    if i not in vocab_other_info: vocab_other_info.append(i)
    #unique_extra_info_dict[i] = unique_extra_info_dict.get(i,0)+1

In [96]:
other_info_token = CountVectorizer(vocabulary=vocab_other_info, tokenizer=lambda x: x.split(' ')).fit(corpus_other_info)

In [103]:
other_info_token = pd.DataFrame(other_info_token.transform(corpus_other_info).toarray(), columns=other_info_token.get_feature_names())

__Clean last_pos_time__

In [20]:
last_time = listings['last_pos_time'].values

In [21]:
last_time_list = []
for i in last_time:
    try:
        t = datetime.strptime(i, '%Y-%m-%d %H:%M')
    except:
        print(i)
        t = None
    last_time_list.append(t)

In [22]:
last_time_df = pd.Series(last_time_list, name = 'last_time_pos')

In [23]:
last_time_df.head()

0   2018-10-24 19:07:00
1   2018-10-24 19:06:00
2   2018-10-24 19:06:00
3   2018-10-24 19:06:00
4   2018-10-24 19:06:00
Name: last_time_pos, dtype: datetime64[ns]

__Cleaning Latitude and Longitude__

In [24]:
latlon = listings[['latitude', 'longitude']].astype('float64')

__Cleaning place__

In [25]:
place_ser = listings['place'].values
place_list = []
for place in place_ser:
    try:
        p = re.findall('[\w ]+', place)[0]
    except:
        p = None
    place_list.append(p)

In [26]:
place_df = pd.Series(place_list, name='place')
place_df.head()

0    san jose north
1            novato
2    san jose north
3           albany
4           marina
Name: place, dtype: object

__Concatenate all__

In [115]:
listings_clean = pd.concat([latlon, place_df, cost, date_time_df, last_time_df, extra_info_df, other_info_token], axis = 1)

In [116]:
listings_clean

,latitude,longitude,place,cost,datetime_posted,datetime_update,last_time_pos,availability,bathroom,bedroom,...,w/d-hookups,duplex,open-house-dates,cottage/cabin,flat,in-law,valet-parking,no-parking,loft,land
0,37.402847,-121.924755,san jose north,3300.0,2018-10-15 16:37:00,2018-10-24 19:02:00,2018-10-24 19:07:00,oct 31,2.5,2.0,...,0,0,0,0,0,0,0,0,0,0
1,NaN,NaN,novato,2399.0,NaT,NaT,2018-10-24 19:06:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2,37.402847,-121.924755,san jose north,3300.0,2018-10-17 00:04:00,2018-10-24 19:02:00,2018-10-24 19:06:00,oct 31,2.5,2.0,...,0,0,0,0,0,0,0,0,0,0
3,37.901258,-122.308644,albany,2875.0,2018-10-24 19:02:00,NaT,2018-10-24 19:06:00,dec 1,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0
4,37.796670,-122.438779,marina,3695.0,2018-10-24 19:02:00,NaT,2018-10-24 19:06:00,None,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
5,38.008321,-121.864673,None,1649.0,2018-09-26 13:35:00,2018-10-24 19:00:00,2018-10-24 19:05:00,None,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
6,37.553177,-121.975581,fremont,2443.0,2018-10-24 19:01:00,NaT,2018-10-24 19:05:00,None,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
7,38.002095,-121.822462,pittsburg,1800.0,2018-10-05 13:24:00,2018-10-24 18:59:00,2018-10-24 19:04:00,oct 1,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0
8,37.349200,-121.953000,santa clara,1450.0,2018-10-24 19:00:00,NaT,2018-10-24 19:04:00,None,2.0,2.0,...,0,0,0,0,0,0,0,0,0,0
9,38.006600,-122.263700,hercules,800.0,2018-10-24 18:47:00,NaT,2018-10-24 19:03:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
10,38.002195,-121.822439,pittsburg,1800.0,2018-10-05 13:23:00,2018-10-24 18:57:00,2018-10-24 19:02:00,oct 25,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0
11,NaN,NaN,fairfax,1050.0,NaT,NaT,2018-10-24 19:02:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
12,37.411674,-121.898987,None,2999.0,2018-10-20 17:56:00,2018-10-24 18:57:00,2018-10-24 19:02:00,oct 20,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
13,37.778256,-122.434716,alamo square,4198.0,2018-10-05 10:40:00,2018-10-24 18:56:00,2018-10-24 19:01:00,oct 6,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0
14,37.762700,-122.442229,castro,2895.0,2018-10-24 18:57:00,NaT,2018-10-24 19:01:00,None,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
15,37.887915,-122.509528,mill valley,1650.0,2018-10-24 18:09:00,NaT,2018-10-24 18:59:00,dec 1,2.0,2.0,...,0,0,0,0,0,0,0,0,0,0
16,37.750900,-122.415300,mountain view,28.0,2018-10-24 18:55:00,NaT,2018-10-24 18:59:00,oct 25,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
17,37.860100,-122.494600,sausalito,2500.0,2018-10-24 18:54:00,NaT,2018-10-24 18:58:00,nov 1,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
18,37.655134,-122.491585,pacifica,3770.0,2018-10-17 16:45:00,2018-10-24 18:53:00,2018-10-24 18:58:00,nov 1,2.0,2.0,...,0,0,0,0,0,0,0,0,0,0
19,37.759300,-122.483600,ingleside,3300.0,2018-10-24 18:54:00,NaT,2018-10-24 18:58:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
20,37.988121,-122.042773,concord,1900.0,2018-10-05 13:25:00,2018-10-24 18:51:00,2018-10-24 18:56:00,oct 15,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0
21,37.743991,-121.429858,dublin,1395.0,2018-10-24 18:39:00,NaT,2018-10-24 18:56:00,oct 24,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
22,37.344537,-121.857838,san jose downtown,3450.0,2018-10-24 18:34:00,NaT,2018-10-24 18:56:00,oct 13,2.5,4.0,...,0,0,0,0,0,0,0,0,0,0
23,37.795700,-122.242900,oakland lake merritt,3200.0,2018-10-17 11:15:00,2018-10-24 18:51:00,2018-10-24 18:56:00,None,2.0,4.0,...,0,0,0,0,0,0,0,0,0,0
24,37.380497,-122.054558,sunnyvale,2650.0,2018-10-24 18:52:00,NaT,2018-10-24 18:56:00,None,1.5,2.0,...,1,0,0,0,0,0,0,0,0,0
25,37.537336,-122.018872,fremont,4500.0,2018-10-07 10:20:00,2018-10-24 18:51:00,2018-10-24 18:56:00,jun 20,4.0,5.0,...,0,0,0,0,0,0,0,0,0,0
26,37.558468,-121.995997,fremont,2799.0,2018-10-24 18:51:00,NaT,2018-10-24 18:55:00,oct 24,2.0,2.0,...,0,0,0,0,0,0,0,0,0,0
27,37.418000,-122.127400,palo alto,4050.0,2018-10-24 18:51:00,NaT,2018-10-24 18:55:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
28,37.444300,-122.149700,palo alto,3525.0,2018-10-24 18:51:00,NaT,2018-10-24 18:55:00,oct 8,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0
29,37.418000,-122.127400,palo alto,2345.0,2018-10-24 18:51:00,NaT,2018-10-24 18:55:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,37.844026,-122.295580,emeryville,2638.0,2018-10-24 12:34:00,NaT,2018-10-24 12:38:00,oct 24,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2971,37.718829,-122.147876,san leandro,2445.0,2018-10-24 12:24:00,NaT,2018-10-24 12:38:00,oct 27,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0
2972,37.584824,-122.017539,fremont,2300.0,2018-10-19 10:26:00,2018-10-24 12:33:00,2018-10-24 12:38:00,oct 21,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0
2973,37.844026,-122.295580,emeryville,2346.0,2018-10-24 12:34:00,NaT,2018-10-24 12:38:00,oct 24,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2974,37.384883,-122.003673,sunnyvale,2735.0,2018-10-24 12:33:00,NaT,2018-10-24 12:37:00,oct 24,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2975,37.789951,-122.410433,nob hill,2400.0,2018-10-24 12:33:00,NaT,2018-10-24 12:37:00,nov 1,1.0,2.0,...,0,0,0,0,0,0,0,1,0,0
2976,37.330468,-121.883527,Downtown San Jose,1995.0,2018-10-09 12:09:00,2018-10-24 12:32:00,2018-10-24 12:37:00,nov 1,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2977,37.663004,-121.865793,dublin,1895.0,2018-10-24 12:33:00,NaT,2018-10-24 12:37:00,None,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2978,37.349537,-121.953499,santa clara,3080.0,2018-10-24 12:33:00,NaT,2018-10-24 12:37:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2979,37.655134,-122.491585,pacifica,2650.0,2018-10-20 11:04:00,2018-10-24 12:32:00,2018-10-24 12:37:00,nov 1,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2980,37.763600,-121.915500,dublin,3132.0,2018-10-24 12:33:00,NaT,2018-10-24 12:37:00,None,2.0,3.0,...,0,0,0,0,0,0,0,0,0,0
2981,37.569135,-122.265678,foster city,3200.0,2018-10-24 12:33:00,NaT,2018-10-24 12:37:00,oct 24,1.5,2.0,...,0,0,0,0,0,0,0,0,0,0
2982,37.530800,-121.971200,fremont,3861.0,2018-10-24 12:33:00,NaT,2018-10-24 12:37:00,None,2.0,3.0,...,0,0,0,0,0,0,0,0,0,0
2983,37.844026,-122.295580,emeryville,3411.0,2018-10-24 12:32:00,NaT,2018-10-24 12:36:00,nov 5,2.0,2.0,...,0,0,0,0,0,0,0,0,0,0
2984,37.349537,-121.953499,santa clara,2430.0,2018-10-24 12:32:00,NaT,2018-10-24 12:36:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2985,38.409289,-122.712741,santa rosa,1690.0,2018-10-06 09:54:00,2018-10-24 12:32:00,2018-10-24 12:36:00,oct 24,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2986,37.859052,-122.128765,lafayette,2395.0,2018-10-08 11:32:00,2018-10-24 12:31:00,2018-10-24 12:36:00,oct 8,1.5,2.0,...,0,0,0,0,0,0,0,0,0,0
2987,37.663004,-121.865793,dublin,1895.0,2018-10-22 11:28:00,2018-10-24 12:31:00,2018-10-24 12:36:00,None,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2988,37.324542,-122.008870,cupertino,3995.0,2018-10-24 12:32:00,NaT,2018-10-24 12:36:00,oct 24,2.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2989,37.352872,-121.987039,santa clara,1795.0,2018-10-17 13:01:00,2018-10-24 12:31:00,2018-10-24 12:36:00,nov 26,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2990,37.878326,-122.522885,mill valley,11000.0,2018-10-24 12:32:00,2018-10-24 13:22:00,2018-10-24 12:36:00,dec 1,4.0,4.0,...,0,0,0,0,0,0,0,0,0,0
2991,37.840426,-122.197578,oakland hills,4500.0,2018-10-19 01:29:00,2018-10-24 12:31:00,2018-10-24 12:36:00,oct 1,2.5,4.0,...,0,0,0,0,0,0,0,0,0,0
2992,37.531936,-122.308480,san mateo,5100.0,2018-10-24 12:32:00,2018-10-24 12:37:00,2018-10-24 12:36:00,nov 3,1.5,3.0,...,0,0,0,0,0,0,0,0,0,0
2993,37.970926,-122.533758,san rafael,1900.0,2018-10-24 12:31:00,NaT,2018-10-24 12:35:00,None,2.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2994,37.396734,-122.011791,sunnyvale,5389.0,2018-10-24 12:31:00,NaT,2018-10-24 12:35:00,oct 24,2.0,2.0,...,0,0,1,0,0,0,0,0,0,0
2995,37.757306,-122.491737,sunset,6295.0,2018-09-28 10:39:00,2018-10-24 12:30:00,2018-10-24 12:35:00,oct 4,4.0,4.0,...,0,0,0,0,0,0,0,0,0,0
2996,37.970926,-122.533758,san rafael,1900.0,2018-10-24 12:31:00,NaT,2018-10-24 12:35:00,None,2.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2997,37.785248,-122.439873,pacific heights,3995.0,2018-10-04 16:10:00,2018-10-24 12:30:00,2018-10-24 12:35:00,oct 4,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0
2998,37.769428,-122.403979,None,4072.0,2018-10-24 12:31:00,NaT,2018-10-24 12:35:00,oct 24,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2999,37.800206,-122.426001,marina,2350.0,2018-10-24 12:31:00,NaT,2018-10-24 12:35:00,None,1.0,0.0,...,0,0,0,0,0,0,0,1,0,0

In [125]:
listings_clean.sort_values('cost', ascending=False)

,latitude,longitude,place,cost,datetime_posted,datetime_update,last_time_pos,availability,bathroom,bedroom,...,w/d-hookups,duplex,open-house-dates,cottage/cabin,flat,in-law,valet-parking,no-parking,loft,land
2382,37.885432,-122.459910,tiburon,49000.0,2018-10-15 13:15:00,2018-10-24 13:40:00,2018-10-24 13:45:00,jun 29,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0
2163,37.787213,-122.391949,SOMA,31710.0,2018-10-24 14:08:00,NaT,2018-10-24 14:12:00,dec 29,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2852,40.666900,-73.982800,Carroll Street,19000.0,2018-09-25 05:05:00,2018-10-24 12:35:00,2018-10-24 12:50:00,dec 31,3.0,3.0,...,0,0,0,0,0,0,0,0,0,0
959,37.790223,-122.432421,pacific heights,18000.0,2018-10-19 14:14:00,2018-10-24 16:29:00,2018-10-24 16:34:00,None,4.0,3.0,...,0,0,0,0,0,0,0,0,0,0
929,37.792569,-122.409279,nob hill,16500.0,2018-10-05 16:30:00,2018-10-24 16:30:00,2018-10-24 16:35:00,None,4.0,4.0,...,0,0,0,0,0,0,0,0,0,0
2617,37.487266,-122.253389,san carlos,16500.0,2018-10-12 08:57:00,2018-10-24 13:09:00,2018-10-24 13:14:00,oct 15,5.5,6.0,...,0,0,0,0,0,0,0,0,0,0
2814,37.791551,-122.410760,nob hill,13000.0,2018-10-04 09:55:00,2018-10-24 12:48:00,2018-10-24 12:53:00,jun 1,4.0,4.0,...,0,0,0,0,0,0,0,0,0,0
2589,37.785741,-122.436254,lower pac hts,12995.0,2018-10-16 11:10:00,NaT,2018-10-24 13:17:00,jan 1,2.5,4.0,...,0,0,0,0,1,0,0,0,0,0
2611,37.792287,-122.443206,pacific heights,12750.0,2018-10-16 11:09:00,NaT,2018-10-24 13:15:00,jan 8,4.0,3.0,...,0,0,0,0,0,0,0,0,0,0
2568,36.965250,-121.961371,santa cruz,12000.0,2018-10-24 13:16:00,NaT,2018-10-24 13:20:00,None,2.5,3.0,...,0,0,0,0,0,0,0,0,0,0
2741,37.791700,-122.418600,nob hill,11500.0,2018-10-24 12:55:00,NaT,2018-10-24 12:59:00,oct 27,2.0,4.0,...,0,0,0,0,0,0,0,0,0,0
2990,37.878326,-122.522885,mill valley,11000.0,2018-10-24 12:32:00,2018-10-24 13:22:00,2018-10-24 12:36:00,dec 1,4.0,4.0,...,0,0,0,0,0,0,0,0,0,0
1229,37.785768,-122.405823,SOMA,10500.0,2018-10-24 15:59:00,NaT,2018-10-24 16:03:00,oct 24,2.5,2.0,...,0,0,0,0,0,0,0,0,0,0
1222,37.785750,-122.405799,financial district,10500.0,2018-10-24 15:58:00,NaT,2018-10-24 16:04:00,oct 24,2.5,2.0,...,0,0,0,0,0,0,0,0,0,0
307,37.447129,-122.133293,palo alto,10500.0,2018-10-24 17:50:00,NaT,2018-10-24 17:54:00,dec 15,3.5,4.0,...,0,0,0,0,0,0,0,0,0,0
2508,37.856762,-122.489619,sausalito,10500.0,2018-10-24 13:23:00,NaT,2018-10-24 13:27:00,None,3.5,4.0,...,0,0,0,0,0,0,0,0,0,0
960,37.786040,-122.401220,SOMA,10000.0,2018-10-16 15:43:00,2018-10-24 16:29:00,2018-10-24 16:34:00,jan 6,2.5,2.0,...,0,0,0,0,0,0,1,0,0,0
418,37.784917,-122.397496,SOMA,10000.0,2018-10-24 17:37:00,NaT,2018-10-24 17:41:00,nov 1,2.5,3.0,...,0,0,0,0,0,0,0,0,0,0
2154,37.369571,-122.116141,los altos,9950.0,2018-10-17 09:17:00,2018-10-24 14:08:00,2018-10-24 14:13:00,None,2.0,5.0,...,1,0,0,0,0,0,0,0,0,0
904,37.784481,-122.450136,laurel hts,9900.0,2018-10-24 16:33:00,NaT,2018-10-24 16:37:00,oct 24,3.0,3.0,...,0,0,0,0,0,0,0,0,0,0
2665,37.752136,-122.433439,noe valley,9900.0,2018-10-22 11:44:00,2018-10-24 13:04:00,2018-10-24 13:09:00,oct 22,4.0,5.0,...,0,0,0,0,0,0,0,0,0,0
215,37.797181,-122.442279,marina,9800.0,2018-10-24 18:02:00,NaT,2018-10-24 18:06:00,None,2.5,2.0,...,0,0,0,0,0,0,0,0,0,0
2809,37.784099,-122.456825,laurel hts,9500.0,2018-10-19 16:21:00,2018-10-24 12:49:00,2018-10-24 12:54:00,nov 1,4.0,4.0,...,0,0,0,0,0,0,0,0,0,0
2550,37.754267,-122.409243,mission district,9400.0,2018-09-26 15:14:00,2018-10-24 13:17:00,2018-10-24 13:22:00,jun 27,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2654,37.792786,-122.424953,pacific heights,9400.0,2018-10-22 12:02:00,2018-10-24 13:04:00,2018-10-24 13:09:00,oct 22,2.0,3.0,...,0,0,0,0,1,0,0,0,0,0
1266,37.785656,-122.405864,financial district,9000.0,2018-10-24 15:55:00,NaT,2018-10-24 15:59:00,oct 24,2.5,2.0,...,0,0,0,0,0,0,0,0,0,0
1281,37.785656,-122.405864,SOMA,9000.0,2018-10-24 15:54:00,NaT,2018-10-24 15:58:00,oct 24,2.5,2.0,...,0,0,0,0,0,0,0,0,0,0
1418,37.791700,-122.418600,marina,8900.0,2018-10-24 15:37:00,NaT,2018-10-24 15:41:00,oct 24,3.5,3.0,...,0,0,0,0,0,0,0,0,0,0
1426,37.794895,-122.429989,pacific heights,8900.0,2018-10-24 15:36:00,NaT,2018-10-24 15:40:00,oct 24,3.5,3.0,...,0,0,0,0,0,0,0,0,0,0
2874,37.801653,-122.403355,north beach,8500.0,2018-10-24 12:44:00,NaT,2018-10-24 12:48:00,oct 24,2.0,2.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1209,38.335494,-121.983903,fairfield,1066.0,2018-10-24 16:01:00,NaT,2018-10-24 16:05:00,oct 24,1.0,2.0,...,0,0,1,0,0,0,0,0,0,0
11,NaN,NaN,fairfax,1050.0,NaT,NaT,2018-10-24 19:02:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
512,37.053533,-122.002316,scotts valley,1050.0,2018-10-24 17:26:00,NaT,2018-10-24 17:30:00,oct 26,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2593,38.628400,-121.328700,Carmichael,1050.0,2018-10-24 13:13:00,NaT,2018-10-24 13:17:00,nov 26,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
670,37.341321,-121.869342,san jose downtown,1025.0,2018-10-24 17:06:00,NaT,2018-10-24 17:10:00,oct 15,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
191,37.772500,-122.414700,SOMA,1000.0,2018-10-24 17:38:00,NaT,2018-10-24 18:10:00,None,1.0,0.0,...,0,0,0,0,0,0,1,0,0,0
165,37.993900,-121.808900,Antioch,1000.0,2018-10-24 17:58:00,NaT,2018-10-24 18:14:00,None,2.5,2.0,...,0,0,0,0,0,0,0,0,0,0
2118,37.848037,-120.217811,Groveland,975.0,2018-10-08 09:27:00,2018-10-24 14:12:00,2018-10-24 14:17:00,oct 15,1.5,2.0,...,0,0,0,0,0,0,0,0,0,0
581,38.105183,-122.262211,vallejo,950.0,2018-10-24 17:17:00,NaT,2018-10-24 17:21:00,oct 24,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2532,38.466584,-123.015367,russian river,935.0,2018-10-24 13:20:00,2018-10-24 13:34:00,2018-10-24 13:24:00,nov 1,1.0,0.0,...,0,0,1,0,0,0,0,0,0,0
1944,NaN,NaN,mountain view,890.0,NaT,NaT,2018-10-24 14:35:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
71,37.294142,-121.960868,campbell,850.0,2018-10-24 18:12:00,NaT,2018-10-24 18:40:00,None,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
1888,38.437455,-123.114338,russian river,850.0,2018-10-22 11:56:00,2018-10-24 14:37:00,2018-10-24 14:42:00,jun 1,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
1890,38.942100,-122.777700,russian river,850.0,2018-09-26 21:38:00,2018-10-24 14:37:00,2018-10-24 14:42:00,oct 31,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1
9,38.006600,-122.263700,hercules,800.0,2018-10-24 18:47:00,NaT,2018-10-24 19:03:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
1771,37.311698,-121.891591,san jose east,800.0,2018-10-24 14:52:00,NaT,2018-10-24 14:56:00,oct 24,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2861,37.781300,-122.416700,bayview,800.0,2018-10-24 12:10:00,NaT,2018-10-24 12:49:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
188,37.698864,-122.461883,daly city,800.0,2018-10-24 18:06:00,NaT,2018-10-24 18:10:00,oct 25,1.0,1.0,...,0,0,0,0,0,1,0,0,0,0
510,39.260702,-123.225918,mendocino county,795.0,2018-10-24 17:26:00,NaT,2018-10-24 17:30:00,None,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0
1123,NaN,NaN,3430 Concord Blvd,750.0,NaT,NaT,2018-10-24 16:15:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
1130,37.984100,-122.011900,3430 Concord Blvd,750.0,2018-10-24 16:10:00,NaT,2018-10-24 16:14:00,None,1.5,3.0,...,0,0,0,0,0,0,0,0,0,0
1124,37.984100,-122.011900,3430 Concord Blvd,750.0,2018-10-24 16:11:00,NaT,2018-10-24 16:15:00,None,1.5,3.0,...,0,0,0,0,0,0,0,0,0,0
1122,37.984100,-122.011900,3430 Concord Blvd,750.0,2018-10-24 16:11:00,NaT,2018-10-24 16:15:00,None,1.5,3.0,...,0,0,0,0,0,0,0,0,0,0
725,NaN,NaN,hayward,700.0,2018-10-24 16:59:00,NaT,2018-10-24 17:03:00,nov 1,NaN,1.0,...,0,0,0,0,0,0,0,0,0,0
711,37.232900,-121.787500,Santa Teresa,650.0,2018-10-24 16:51:00,NaT,2018-10-24 17:06:00,oct 20,NaN,1.0,...,0,0,0,0,0,0,0,0,0,0
16,37.750900,-122.415300,mountain view,28.0,2018-10-24 18:55:00,NaT,2018-10-24 18:59:00,oct 25,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
799,37.750900,-122.415300,All Bay Area,28.0,2018-10-24 16:48:00,NaT,2018-10-24 16:52:00,oct 25,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
625,37.355686,-122.014319,sunnyvale,1.0,2018-10-24 17:11:00,NaT,2018-10-24 17:15:00,oct 25,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
1635,37.770600,-122.264800,oakland piedmont,NaN,2018-10-24 15:12:00,NaT,2018-10-24 15:16:00,None,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2893,37.628819,-122.489832,pacifica,NaN,2018-10-24 12:42:00,NaT,2018-10-24 12:46:00,None,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0